name: CI/CD

on:
  push:
    branches:
      - devel
      - release

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push backend
      run: |
        cd backend
        docker build -t ${{ secrets.DOCKER_USERNAME }}/sloventure-backend:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/sloventure-backend:latest

    - name: Use production .env for frontend
      run: cp frontend/.env.production frontend/.env
    
    - name: Build and push frontend
      run: |
        cd ../frontend
        docker build -t ${{ secrets.DOCKER_USERNAME }}/sloventure-frontend:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/sloventure-frontend:latest

    - name: Trigger webhook on Azure
      uses: distributhor/webhook-action@v2
      with:
        url: ${{ secrets.WEBHOOK_URL }}
        method: POST
        body: '{"event":"new_release"}'
        headers: |
          Content-Type: application/json
          X-Hook-Secret: ${{ secrets.WEBHOOK_SECRET }}