name: CI/CD

on:
  push:
    branches:
      - develop
      - release
      - SCRUM-93-Neprekinjena-integracija-in-neprekinjena-dostava

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Generate .env.production file for backend
      run: |
        echo "${{ secrets.BACKEND_ENV_PRODUCTION }}" > SloVenture/backend/.env

    - name: Build and push backend
      run: |
        cd SloVenture/backend
        docker build -t ${{ secrets.DOCKER_USERNAME }}/sloventure-backend:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/sloventure-backend:latest

    - name: Generate .env.production file for frontend
      run: |
        echo "${{ secrets.FRONTEND_ENV_PRODUCTION }}" > SloVenture/frontend/.env
    
    - name: Build and push frontend
      run: |
        cd SloVenture/frontend
        docker build -t ${{ secrets.DOCKER_USERNAME }}/sloventure-frontend:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/sloventure-frontend:latest

    - name: Trigger webhook on Azure
      uses: distributhor/workflow-webhook@v3
      with:
        webhook_url: ${{ secrets.WEBHOOK_URL }}
        webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
        event_name: new_release
        data: '{"message":"Deployment triggered"}'