name: Test Frontend

on:
  push:
    paths:
      - 'SloVenture/frontend/**'
  pull_request:
    paths:
      - 'SloVenture/frontend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: SloVenture/frontend

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Generate .env.production file for frontend
      run: |
        echo "${{ secrets.FRONTEND_ENV_PRODUCTION }}" > .env

    - name: Run tests
      run: npm test
